version: "2"
run:
  tests: true
linters:
  enable:
    - bodyclose
    - copyloopvar
    - exhaustive
    - funlen
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - noctx
    - prealloc
    - unconvert
    - unparam
  settings:
    funlen:
      lines: 80
      statements: 50
    gocritic:
      disabled-checks:
        - hugeParam
      enabled-tags:
        - diagnostic
        - performance
        - style
    gocyclo:
      min-complexity: 15
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - funlen
          - gocyclo
          - gosec
          - unparam
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
